name: Go CI

on: [push, pull_request]

jobs:
    inspect-code:
        runs-on: ubantu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v5
            with:
                go-version: 'stable'
            
          - name: Build App
            run: go build .

