name: Build

on: [push, pull_request]

jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: 'stable'
            
            - name: Check Formatting 
              uses: test -z "$(gofmt -l .)"

            - name: Code Analysis (Vet)
              uses: go vet ./...

            - name: Build app
              run: go build .